# Generated by Django 5.1.6 on 2025-02-05 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=150)),
                ('title_ru', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MiddleCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=150)),
                ('title_ru', models.CharField(max_length=150)),
                ('top_catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middle_catalogue', to='catalogues.topcatalogue', verbose_name='Top Catalogue')),
            ],
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=150)),
                ('title_ru', models.CharField(max_length=150)),
                ('middle_catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue', to='catalogues.topcatalogue', verbose_name='Middle Catalogue')),
            ],
        ),
    ]
