# Generated by Django 5.1.6 on 2025-02-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='restaurant',
            field=models.ManyToManyField(editable=False, related_name='catalogues', to='restaurants.restaurant', verbose_name='Restaurants'),
        ),
    ]
