# Generated by Django 5.1.6 on 2025-02-05 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='middle_catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue', to='catalogues.middlecatalogue', verbose_name='Middle Catalogue'),
        ),
    ]
