# Generated by Django 5.1.6 on 2025-02-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0002_alter_catalogue_middle_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='middlecatalogue',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='topcatalogue',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
