# Generated by Django 5.1.6 on 2025-02-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0003_catalogue_slug_middlecatalogue_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='middlecatalogue',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='topcatalogue',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
