# Generated by Django 5.1.6 on 2025-02-05 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0005_remove_middlecatalogue_top_catalogue_and_more'),
        ('products', '0009_remove_product_middle_catalogue_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopCatalogue',
        ),
        migrations.DeleteModel(
            name='MiddleCatalogue',
        ),
    ]
