# Generated by Django 5.1.6 on 2025-02-06 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0006_delete_topcatalogue_delete_middlecatalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcatalogues', to='catalogues.catalogue', verbose_name='Parent catalogue'),
        ),
    ]
