# Generated by Django 5.1.6 on 2025-02-05 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EtrapCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
                ('city_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_province', to='locations.cityprovince', verbose_name='CityProvince')),
            ],
        ),
        migrations.CreateModel(
            name='AddressLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
                ('etrap_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etrap_city', to='locations.etrapcity', verbose_name='EtrapCity')),
            ],
        ),
    ]
