# Generated by Django 5.1.6 on 2025-02-06 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_addressline_slug_cityprovince_slug_etrapcity_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressline',
            name='etrap_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_line', to='locations.etrapcity', verbose_name='EtrapCity'),
        ),
        migrations.AlterField(
            model_name='etrapcity',
            name='city_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etrap_city', to='locations.cityprovince', verbose_name='CityProvince'),
        ),
    ]
