# Generated by Django 5.1.6 on 2025-02-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_city_province'),
        ('locations', '0003_alter_addressline_etrap_city_and_more'),
        ('restaurants', '0005_remove_restaurant_city_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etrapcity',
            name='city_province',
        ),
        migrations.DeleteModel(
            name='CityProvince',
        ),
    ]
