# Generated by Django 5.1.6 on 2025-02-07 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_address_line_remove_user_etrap_city'),
        ('locations', '0004_remove_etrapcity_city_province_delete_cityprovince'),
        ('restaurants', '0005_remove_restaurant_city_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressline',
            name='etrap_city',
        ),
        migrations.RenameModel(
            old_name='EtrapCity',
            new_name='Location',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='locations.location', verbose_name='Location')),
            ],
        ),
    ]
