# Generated by Django 5.1.6 on 2025-02-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_remove_addressline_etrap_city_and_more'),
        ('restaurants', '0006_remove_restaurant_address_line_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressLine',
        ),
    ]
