# Generated by Django 5.1.6 on 2025-02-06 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('locations', '0003_alter_addressline_etrap_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address_line', to='locations.addressline', verbose_name='AddressLine'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_city_province', to='locations.cityprovince', verbose_name='CityProvince'),
        ),
        migrations.AddField(
            model_name='user',
            name='etrap_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_etrap_city', to='locations.etrapcity', verbose_name='EtrapCity'),
        ),
    ]
