# Generated by Django 5.1.6 on 2025-02-06 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
