# Generated by Django 5.1.6 on 2025-02-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city_province',
        ),
    ]
