# Generated by Django 5.1.6 on 2025-02-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_city_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='user',
            name='etrap_city',
        ),
    ]
