# Generated by Django 5.1.6 on 2025-02-07 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_address_line_remove_user_etrap_city'),
        ('locations', '0005_remove_addressline_etrap_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='locations.address', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to='locations.location', verbose_name='Location'),
        ),
    ]
