# Generated by Django 5.1.6 on 2025-02-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_address_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_delivery_man',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_restaurant_customer',
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('admin', 'admin'), ('customer', 'Customer'), ('delivery', 'Delivery'), ('client', 'Client')], default='customer', max_length=100),
        ),
    ]
