# Generated by Django 5.1.6 on 2025-02-07 16:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_is_customer_remove_user_is_delivery_man_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='CustomerUser',
        ),
        migrations.DeleteModel(
            name='DeliveryManUser',
        ),
        migrations.DeleteModel(
            name='RestaurantCustomerUser',
        ),
        migrations.AddField(
            model_name='user',
            name='car_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.account_car_image_upload_path),
        ),
        migrations.AddField(
            model_name='user',
            name='car_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='car_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.account_image_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('staff', 'Staff'), ('admin', 'Admin'), ('customer', 'Customer'), ('delivery', 'Delivery'), ('client', 'Client')], default='customer', max_length=100),
        ),
    ]
