# Generated by Django 5.1.6 on 2025-02-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_order_price_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('active', 'Active'), ('accepted', 'Accepted'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='pending'),
        ),
    ]
