# Generated by Django 5.1.6 on 2025-02-15 22:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
                ('description_tm', models.TextField()),
                ('description_ru', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, editable=False, null=True, upload_to='')),
                ('original_image', models.ImageField(upload_to='')),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('price', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('date_added', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='catalogues.catalogue', verbose_name='Catalogue')),
            ],
        ),
    ]
