# Generated by Django 5.1.6 on 2025-02-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
