# Generated by Django 5.1.6 on 2025-02-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(default='fws'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description_tm',
            field=models.TextField(default='few'),
            preserve_default=False,
        ),
    ]
