# Generated by Django 5.1.6 on 2025-02-05 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0002_alter_catalogue_middle_catalogue'),
        ('products', '0005_product_discount_product_initial_price_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='catalogues.catalogue', verbose_name='Catalogue of the Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='middle_catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='catalogues.middlecatalogue', verbose_name='Middle Catalogue of the Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='catalogues.topcatalogue', verbose_name='Top Catalogue of the Product'),
        ),
    ]
