# Generated by Django 5.1.6 on 2025-02-05 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_catalogue_product_middle_catalogue_and_more'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='restaurants.restaurant', verbose_name='Restaurant of the Product'),
            preserve_default=False,
        ),
    ]
