# Generated by Django 5.1.6 on 2025-02-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
