# Generated by Django 5.1.6 on 2025-02-05 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0005_remove_middlecatalogue_top_catalogue_and_more'),
        ('products', '0008_product_active_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='middle_catalogue',
        ),
        migrations.RemoveField(
            model_name='product',
            name='top_catalogue',
        ),
        migrations.AlterField(
            model_name='product',
            name='catalogue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='catalogues.catalogue', verbose_name='Catalogue of the Product'),
            preserve_default=False,
        ),
    ]
