# Generated by Django 5.1.6 on 2025-02-05 20:59

import restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=150)),
                ('title_ru', models.CharField(max_length=150)),
                ('description_tm', models.TextField()),
                ('description_ru', models.TextField()),
                ('image', models.ImageField(upload_to=restaurants.models.restaurant_image_upload_path)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
    ]
