# Generated by Django 5.1.6 on 2025-02-15 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, editable=False, null=True, upload_to='')),
                ('original_image', models.ImageField(upload_to='')),
                ('date_added', models.DateTimeField(blank=True, editable=False, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('is_active', models.BooleanField()),
                ('is_online', models.BooleanField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_address', to='locations.address', verbose_name='Address')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_location', to='locations.location', verbose_name='Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
