# Generated by Django 5.1.6 on 2025-02-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
    ]
