# Generated by Django 5.1.6 on 2025-02-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='original_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
