# Generated by Django 5.1.6 on 2025-02-05 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('restaurants', '0002_restaurant_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_address_line', to='locations.addressline', verbose_name='AddressLine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city_province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_city_province', to='locations.cityprovince', verbose_name='CityProvince'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='etrap_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_etrap_city', to='locations.etrapcity', verbose_name='EtrapCity'),
            preserve_default=False,
        ),
    ]
