# Generated by Django 5.1.6 on 2025-02-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_delivery_free',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_top',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
