# Generated by Django 5.1.6 on 2025-02-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='city_province',
        ),
    ]
