# Generated by Django 5.1.6 on 2025-02-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_is_delivery_free_restaurant_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
