# Generated by Django 5.1.6 on 2025-02-07 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_remove_addressline_etrap_city_and_more'),
        ('restaurants', '0005_remove_restaurant_city_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='etrap_city',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_address', to='locations.address', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_location', to='locations.location', verbose_name='Location'),
        ),
    ]
